#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT="SF Pro"
PADDING=3

# Unload the macOS on screen indicator overlay for volume change
# launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Bar appearance
# https://felixkratz.github.io/SketchyBar/config/bar

bar=(
  height=45
  color="$TRANSPARENT"
  border_width=0
  border_color="$WHITE"
  shadow=off
  position=top
  sticky=on
  padding_right=15
  padding_left=15
  y_offset=0
  margin=0
  topmost=window
)

sketchybar --bar "${bar[@]}"

# Default item configuration
# https://felixkratz.github.io/SketchyBar/config/items

defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color="$ICON_COLOR"
  icon.padding_left="$PADDING"
  icon.padding_right="$PADDING"
  label.font="$FONT:Semibold:13.0"
  label.color="$LABEL_COLOR"
  label.padding_left="$PADDING"
  label.padding_right="$PADDING"
  padding_right="$PADDING"
  padding_left="$PADDING"
  background.height=26
  background.corner_radius=5
  background.border_width=2
  background.border_color="$WHITE"
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color="$POPUP_BORDER_COLOR"
  popup.background.color="$POPUP_BACKGROUND_COLOR"
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
# source "$ITEM_DIR/yabai.sh"
# source "$ITEM_DIR/front_app.sh"

# Center
# source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/media.sh"

# Right
# source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/brew.sh"
# source "$ITEM_DIR/github.sh"
# source "$ITEM_DIR/wifi.sh"
# source "$ITEM_DIR/battery.sh"
# source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/cpu.sh"
# source "$ITEM_DIR/svim.sh"

sketchybar --hotload on

# Force all scripts to run the first time (never do this in a script)
# sketchybar --update
