#!/usr/bin/env sh

# Yabai config
#  - https://github.com/koekeishiya/yabai/wiki/Configuration

# Tiling options ---------------------------------------------------------------

# Layout
yabai -m config layout bsp

# Padding and gaps
yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20

# Split ratios
yabai -m config auto_balance off       # Windows occupy the same amount of space
yabai -m config split_ratio  0.50

# Window borders
yabai -m config window_border on
yabai -m config window_border_width 3 
yabai -m config active_window_border_color 0xFFA6E3A1
yabai -m config normal_window_border_color 0x00FFFFFF

# Rules ------------------------------------------------------------------------

# Apps that shouldn't be managed by Yabai
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off

